# Generated by Django 5.0.3 on 2024-03-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_participant_player_4_participant_player_4_bgmi_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solo',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='Duo',
        ),
        migrations.DeleteModel(
            name='Solo',
        ),
        migrations.DeleteModel(
            name='Squad',
        ),
    ]
